# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/undercover/personal/v/ui_principal.ui'
#
# Created: Fri Jan 23 09:07:23 2015
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Principal(object):
    def setupUi(self, Principal):
        Principal.setObjectName(_fromUtf8("Principal"))
        Principal.resize(873, 537)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("images/personal.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Principal.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(Principal)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pbAgregar = QtGui.QPushButton(self.centralwidget)
        self.pbAgregar.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("images/agregar-empleado.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbAgregar.setIcon(icon1)
        self.pbAgregar.setIconSize(QtCore.QSize(32, 32))
        self.pbAgregar.setObjectName(_fromUtf8("pbAgregar"))
        self.horizontalLayout_3.addWidget(self.pbAgregar)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.leEmpleadoFilter = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leEmpleadoFilter.sizePolicy().hasHeightForWidth())
        self.leEmpleadoFilter.setSizePolicy(sizePolicy)
        self.leEmpleadoFilter.setMinimumSize(QtCore.QSize(256, 0))
        self.leEmpleadoFilter.setObjectName(_fromUtf8("leEmpleadoFilter"))
        self.horizontalLayout_2.addWidget(self.leEmpleadoFilter)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.twEmpleados = QtGui.QTreeWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.twEmpleados.sizePolicy().hasHeightForWidth())
        self.twEmpleados.setSizePolicy(sizePolicy)
        self.twEmpleados.setAlternatingRowColors(True)
        self.twEmpleados.setObjectName(_fromUtf8("twEmpleados"))
        self.horizontalLayout.addWidget(self.twEmpleados)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tDatosEmpleado = QtGui.QWidget()
        self.tDatosEmpleado.setObjectName(_fromUtf8("tDatosEmpleado"))
        self.gridLayout = QtGui.QGridLayout(self.tDatosEmpleado)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.twLicencias = QtGui.QTableWidget(self.tDatosEmpleado)
        self.twLicencias.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.twLicencias.setAlternatingRowColors(True)
        self.twLicencias.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.twLicencias.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.twLicencias.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.twLicencias.setObjectName(_fromUtf8("twLicencias"))
        self.twLicencias.setColumnCount(5)
        self.twLicencias.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.twLicencias.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.twLicencias.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.twLicencias.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.twLicencias.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.twLicencias.setHorizontalHeaderItem(4, item)
        self.twLicencias.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_4.addWidget(self.twLicencias)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.pbLicAgregar = QtGui.QPushButton(self.tDatosEmpleado)
        self.pbLicAgregar.setEnabled(False)
        self.pbLicAgregar.setIconSize(QtCore.QSize(32, 32))
        self.pbLicAgregar.setObjectName(_fromUtf8("pbLicAgregar"))
        self.verticalLayout_3.addWidget(self.pbLicAgregar)
        self.pbLicEditar = QtGui.QPushButton(self.tDatosEmpleado)
        self.pbLicEditar.setEnabled(False)
        self.pbLicEditar.setIconSize(QtCore.QSize(32, 32))
        self.pbLicEditar.setObjectName(_fromUtf8("pbLicEditar"))
        self.verticalLayout_3.addWidget(self.pbLicEditar)
        self.pbLicEliminar = QtGui.QPushButton(self.tDatosEmpleado)
        self.pbLicEliminar.setEnabled(False)
        self.pbLicEliminar.setIconSize(QtCore.QSize(32, 32))
        self.pbLicEliminar.setObjectName(_fromUtf8("pbLicEliminar"))
        self.verticalLayout_3.addWidget(self.pbLicEliminar)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout_4, 4, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.lblEmpleado = QtGui.QLabel(self.tDatosEmpleado)
        self.lblEmpleado.setObjectName(_fromUtf8("lblEmpleado"))
        self.horizontalLayout_5.addWidget(self.lblEmpleado)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.lblTipoLicencia = QtGui.QLabel(self.tDatosEmpleado)
        self.lblTipoLicencia.setObjectName(_fromUtf8("lblTipoLicencia"))
        self.horizontalLayout_5.addWidget(self.lblTipoLicencia)
        self.cmbTipoLicencia = QtGui.QComboBox(self.tDatosEmpleado)
        self.cmbTipoLicencia.setObjectName(_fromUtf8("cmbTipoLicencia"))
        self.cmbTipoLicencia.addItem(_fromUtf8(""))
        self.cmbTipoLicencia.addItem(_fromUtf8(""))
        self.cmbTipoLicencia.addItem(_fromUtf8(""))
        self.cmbTipoLicencia.addItem(_fromUtf8(""))
        self.cmbTipoLicencia.addItem(_fromUtf8(""))
        self.cmbTipoLicencia.addItem(_fromUtf8(""))
        self.cmbTipoLicencia.addItem(_fromUtf8(""))
        self.cmbTipoLicencia.addItem(_fromUtf8(""))
        self.cmbTipoLicencia.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.cmbTipoLicencia)
        self.lblPeriodo = QtGui.QLabel(self.tDatosEmpleado)
        self.lblPeriodo.setObjectName(_fromUtf8("lblPeriodo"))
        self.horizontalLayout_5.addWidget(self.lblPeriodo)
        self.cmbPeriodo = QtGui.QComboBox(self.tDatosEmpleado)
        self.cmbPeriodo.setObjectName(_fromUtf8("cmbPeriodo"))
        self.cmbPeriodo.addItem(_fromUtf8(""))
        self.cmbPeriodo.addItem(_fromUtf8(""))
        self.cmbPeriodo.addItem(_fromUtf8(""))
        self.cmbPeriodo.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.cmbPeriodo)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tDatosEmpleado, _fromUtf8(""))
        self.tDatosLicencias = QtGui.QWidget()
        self.tDatosLicencias.setObjectName(_fromUtf8("tDatosLicencias"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tDatosLicencias)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.lblImagen = QtGui.QLabel(self.tDatosLicencias)
        self.lblImagen.setObjectName(_fromUtf8("lblImagen"))
        self.horizontalLayout_6.addWidget(self.lblImagen)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.pbEditar = QtGui.QPushButton(self.tDatosLicencias)
        self.pbEditar.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("images/editar-empleado.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbEditar.setIcon(icon2)
        self.pbEditar.setIconSize(QtCore.QSize(32, 32))
        self.pbEditar.setObjectName(_fromUtf8("pbEditar"))
        self.verticalLayout_4.addWidget(self.pbEditar)
        self.pbEliminar = QtGui.QPushButton(self.tDatosLicencias)
        self.pbEliminar.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("images/eliminar-empleado.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbEliminar.setIcon(icon3)
        self.pbEliminar.setIconSize(QtCore.QSize(32, 32))
        self.pbEliminar.setObjectName(_fromUtf8("pbEliminar"))
        self.verticalLayout_4.addWidget(self.pbEliminar)
        self.pbGrupoFamiliar = QtGui.QPushButton(self.tDatosLicencias)
        self.pbGrupoFamiliar.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("images/hijos.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbGrupoFamiliar.setIcon(icon4)
        self.pbGrupoFamiliar.setIconSize(QtCore.QSize(32, 32))
        self.pbGrupoFamiliar.setObjectName(_fromUtf8("pbGrupoFamiliar"))
        self.verticalLayout_4.addWidget(self.pbGrupoFamiliar)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.twDatosPersonales = QtGui.QTableWidget(self.tDatosLicencias)
        self.twDatosPersonales.setFrameShape(QtGui.QFrame.NoFrame)
        self.twDatosPersonales.setFrameShadow(QtGui.QFrame.Sunken)
        self.twDatosPersonales.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.twDatosPersonales.setAlternatingRowColors(True)
        self.twDatosPersonales.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.twDatosPersonales.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.twDatosPersonales.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.twDatosPersonales.setRowCount(7)
        self.twDatosPersonales.setColumnCount(2)
        self.twDatosPersonales.setObjectName(_fromUtf8("twDatosPersonales"))
        item = QtGui.QTableWidgetItem()
        self.twDatosPersonales.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.twDatosPersonales.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.twDatosPersonales.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.twDatosPersonales.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.twDatosPersonales.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        self.twDatosPersonales.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        self.twDatosPersonales.setItem(6, 0, item)
        self.twDatosPersonales.horizontalHeader().setVisible(False)
        self.twDatosPersonales.horizontalHeader().setDefaultSectionSize(200)
        self.twDatosPersonales.horizontalHeader().setStretchLastSection(True)
        self.twDatosPersonales.verticalHeader().setVisible(False)
        self.horizontalLayout_7.addWidget(self.twDatosPersonales)
        self.line = QtGui.QFrame(self.tDatosLicencias)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_7.addWidget(self.line)
        self.twDatosLaborales = QtGui.QTableWidget(self.tDatosLicencias)
        self.twDatosLaborales.setFrameShape(QtGui.QFrame.NoFrame)
        self.twDatosLaborales.setFrameShadow(QtGui.QFrame.Sunken)
        self.twDatosLaborales.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.twDatosLaborales.setAlternatingRowColors(True)
        self.twDatosLaborales.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.twDatosLaborales.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.twDatosLaborales.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.twDatosLaborales.setRowCount(7)
        self.twDatosLaborales.setColumnCount(2)
        self.twDatosLaborales.setObjectName(_fromUtf8("twDatosLaborales"))
        item = QtGui.QTableWidgetItem()
        self.twDatosLaborales.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.twDatosLaborales.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.twDatosLaborales.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.twDatosLaborales.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.twDatosLaborales.setItem(4, 0, item)
        self.twDatosLaborales.horizontalHeader().setVisible(False)
        self.twDatosLaborales.horizontalHeader().setDefaultSectionSize(200)
        self.twDatosLaborales.horizontalHeader().setStretchLastSection(True)
        self.twDatosLaborales.verticalHeader().setVisible(False)
        self.horizontalLayout_7.addWidget(self.twDatosLaborales)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.lblObservaciones = QtGui.QLabel(self.tDatosLicencias)
        self.lblObservaciones.setObjectName(_fromUtf8("lblObservaciones"))
        self.horizontalLayout_8.addWidget(self.lblObservaciones)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.pbEditarObservaciones = QtGui.QPushButton(self.tDatosLicencias)
        self.pbEditarObservaciones.setEnabled(False)
        self.pbEditarObservaciones.setObjectName(_fromUtf8("pbEditarObservaciones"))
        self.horizontalLayout_8.addWidget(self.pbEditarObservaciones)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.txtEObservaciones = QtGui.QTextEdit(self.tDatosLicencias)
        self.txtEObservaciones.setEnabled(False)
        self.txtEObservaciones.setObjectName(_fromUtf8("txtEObservaciones"))
        self.verticalLayout_2.addWidget(self.txtEObservaciones)
        self.tabWidget.addTab(self.tDatosLicencias, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidget)
        self.verticalLayout.addLayout(self.horizontalLayout)
        Principal.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Principal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 873, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuArchivo = QtGui.QMenu(self.menubar)
        self.menuArchivo.setObjectName(_fromUtf8("menuArchivo"))
        self.menuAyuda = QtGui.QMenu(self.menubar)
        self.menuAyuda.setObjectName(_fromUtf8("menuAyuda"))
        self.menuEmpleado = QtGui.QMenu(self.menubar)
        self.menuEmpleado.setObjectName(_fromUtf8("menuEmpleado"))
        self.menuLicencia = QtGui.QMenu(self.menubar)
        self.menuLicencia.setObjectName(_fromUtf8("menuLicencia"))
        Principal.setMenuBar(self.menubar)
        self.statusBar = QtGui.QStatusBar(Principal)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        Principal.setStatusBar(self.statusBar)
        self.aSalir = QtGui.QAction(Principal)
        self.aSalir.setObjectName(_fromUtf8("aSalir"))
        self.aReiniciar = QtGui.QAction(Principal)
        self.aReiniciar.setObjectName(_fromUtf8("aReiniciar"))
        self.aAcerca_de = QtGui.QAction(Principal)
        self.aAcerca_de.setObjectName(_fromUtf8("aAcerca_de"))
        self.aAgregar = QtGui.QAction(Principal)
        self.aAgregar.setObjectName(_fromUtf8("aAgregar"))
        self.aEditar = QtGui.QAction(Principal)
        self.aEditar.setEnabled(False)
        self.aEditar.setObjectName(_fromUtf8("aEditar"))
        self.aEliminar = QtGui.QAction(Principal)
        self.aEliminar.setEnabled(False)
        self.aEliminar.setObjectName(_fromUtf8("aEliminar"))
        self.aAgregarLicencia = QtGui.QAction(Principal)
        self.aAgregarLicencia.setEnabled(False)
        self.aAgregarLicencia.setObjectName(_fromUtf8("aAgregarLicencia"))
        self.aEditarLicencia = QtGui.QAction(Principal)
        self.aEditarLicencia.setEnabled(False)
        self.aEditarLicencia.setObjectName(_fromUtf8("aEditarLicencia"))
        self.aEliminarLicencia = QtGui.QAction(Principal)
        self.aEliminarLicencia.setEnabled(False)
        self.aEliminarLicencia.setObjectName(_fromUtf8("aEliminarLicencia"))
        self.actionGrupo_familiar = QtGui.QAction(Principal)
        self.actionGrupo_familiar.setEnabled(False)
        self.actionGrupo_familiar.setObjectName(_fromUtf8("actionGrupo_familiar"))
        self.aGenerarGrafico = QtGui.QAction(Principal)
        self.aGenerarGrafico.setEnabled(False)
        self.aGenerarGrafico.setObjectName(_fromUtf8("aGenerarGrafico"))
        self.menuArchivo.addAction(self.aReiniciar)
        self.menuArchivo.addAction(self.aSalir)
        self.menuAyuda.addAction(self.aAcerca_de)
        self.menuEmpleado.addAction(self.aAgregar)
        self.menuEmpleado.addAction(self.aEditar)
        self.menuEmpleado.addAction(self.aEliminar)
        self.menuEmpleado.addSeparator()
        self.menuEmpleado.addAction(self.actionGrupo_familiar)
        self.menuLicencia.addAction(self.aAgregarLicencia)
        self.menuLicencia.addAction(self.aEditarLicencia)
        self.menuLicencia.addAction(self.aEliminarLicencia)
        self.menuLicencia.addSeparator()
        self.menuLicencia.addAction(self.aGenerarGrafico)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuEmpleado.menuAction())
        self.menubar.addAction(self.menuLicencia.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())

        self.retranslateUi(Principal)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Principal)

    def retranslateUi(self, Principal):
        Principal.setWindowTitle(QtGui.QApplication.translate("Principal", "Personal", None, QtGui.QApplication.UnicodeUTF8))
        self.pbAgregar.setToolTip(QtGui.QApplication.translate("Principal", "Agregar empleado", None, QtGui.QApplication.UnicodeUTF8))
        self.leEmpleadoFilter.setPlaceholderText(QtGui.QApplication.translate("Principal", "Filtrar empleados", None, QtGui.QApplication.UnicodeUTF8))
        self.twEmpleados.headerItem().setText(0, QtGui.QApplication.translate("Principal", "Apellido, Nombre (documento)", None, QtGui.QApplication.UnicodeUTF8))
        self.twLicencias.setSortingEnabled(True)
        item = self.twLicencias.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("Principal", "Tipo", None, QtGui.QApplication.UnicodeUTF8))
        item = self.twLicencias.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("Principal", "Desde", None, QtGui.QApplication.UnicodeUTF8))
        item = self.twLicencias.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("Principal", "Hasta", None, QtGui.QApplication.UnicodeUTF8))
        item = self.twLicencias.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("Principal", "Días", None, QtGui.QApplication.UnicodeUTF8))
        item = self.twLicencias.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("Principal", "Comentario", None, QtGui.QApplication.UnicodeUTF8))
        self.pbLicAgregar.setToolTip(QtGui.QApplication.translate("Principal", "Agregar licencia", None, QtGui.QApplication.UnicodeUTF8))
        self.pbLicAgregar.setText(QtGui.QApplication.translate("Principal", "Agregar...", None, QtGui.QApplication.UnicodeUTF8))
        self.pbLicEditar.setToolTip(QtGui.QApplication.translate("Principal", "Editar licencia", None, QtGui.QApplication.UnicodeUTF8))
        self.pbLicEditar.setText(QtGui.QApplication.translate("Principal", "Editar...", None, QtGui.QApplication.UnicodeUTF8))
        self.pbLicEliminar.setToolTip(QtGui.QApplication.translate("Principal", "Eliminar licencia", None, QtGui.QApplication.UnicodeUTF8))
        self.pbLicEliminar.setText(QtGui.QApplication.translate("Principal", "Eliminar...", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEmpleado.setText(QtGui.QApplication.translate("Principal", "Apellido, Nombre (documento)", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTipoLicencia.setText(QtGui.QApplication.translate("Principal", "Tipo:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbTipoLicencia.setItemText(0, QtGui.QApplication.translate("Principal", "Todas", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbTipoLicencia.setItemText(1, QtGui.QApplication.translate("Principal", "18", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbTipoLicencia.setItemText(2, QtGui.QApplication.translate("Principal", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbTipoLicencia.setItemText(3, QtGui.QApplication.translate("Principal", "53", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbTipoLicencia.setItemText(4, QtGui.QApplication.translate("Principal", "58", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbTipoLicencia.setItemText(5, QtGui.QApplication.translate("Principal", "Comisión", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbTipoLicencia.setItemText(6, QtGui.QApplication.translate("Principal", "Enfermedad", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbTipoLicencia.setItemText(7, QtGui.QApplication.translate("Principal", "Franco", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbTipoLicencia.setItemText(8, QtGui.QApplication.translate("Principal", "Otro", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPeriodo.setText(QtGui.QApplication.translate("Principal", "Período:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbPeriodo.setItemText(0, QtGui.QApplication.translate("Principal", "Histórico", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbPeriodo.setItemText(1, QtGui.QApplication.translate("Principal", "Última semana", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbPeriodo.setItemText(2, QtGui.QApplication.translate("Principal", "Último mes", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbPeriodo.setItemText(3, QtGui.QApplication.translate("Principal", "Último año", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tDatosEmpleado), QtGui.QApplication.translate("Principal", "Licencias", None, QtGui.QApplication.UnicodeUTF8))
        self.lblImagen.setText(QtGui.QApplication.translate("Principal", "Imagen del empleado", None, QtGui.QApplication.UnicodeUTF8))
        self.pbEditar.setToolTip(QtGui.QApplication.translate("Principal", "Editar empleado", None, QtGui.QApplication.UnicodeUTF8))
        self.pbEditar.setText(QtGui.QApplication.translate("Principal", "Editar", None, QtGui.QApplication.UnicodeUTF8))
        self.pbEliminar.setToolTip(QtGui.QApplication.translate("Principal", "Eliminar empleado", None, QtGui.QApplication.UnicodeUTF8))
        self.pbEliminar.setText(QtGui.QApplication.translate("Principal", "Eliminar", None, QtGui.QApplication.UnicodeUTF8))
        self.pbGrupoFamiliar.setToolTip(QtGui.QApplication.translate("Principal", "Administrar hijos", None, QtGui.QApplication.UnicodeUTF8))
        self.pbGrupoFamiliar.setText(QtGui.QApplication.translate("Principal", "Grupo familiar", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.twDatosPersonales.isSortingEnabled()
        self.twDatosPersonales.setSortingEnabled(False)
        item = self.twDatosPersonales.item(0, 0)
        item.setText(QtGui.QApplication.translate("Principal", "Nombre", None, QtGui.QApplication.UnicodeUTF8))
        item = self.twDatosPersonales.item(1, 0)
        item.setText(QtGui.QApplication.translate("Principal", "Apellido", None, QtGui.QApplication.UnicodeUTF8))
        item = self.twDatosPersonales.item(2, 0)
        item.setText(QtGui.QApplication.translate("Principal", "Documento", None, QtGui.QApplication.UnicodeUTF8))
        item = self.twDatosPersonales.item(3, 0)
        item.setText(QtGui.QApplication.translate("Principal", "Fecha de nacimiento", None, QtGui.QApplication.UnicodeUTF8))
        item = self.twDatosPersonales.item(4, 0)
        item.setText(QtGui.QApplication.translate("Principal", "Género", None, QtGui.QApplication.UnicodeUTF8))
        item = self.twDatosPersonales.item(5, 0)
        item.setText(QtGui.QApplication.translate("Principal", "Teléfono", None, QtGui.QApplication.UnicodeUTF8))
        item = self.twDatosPersonales.item(6, 0)
        item.setText(QtGui.QApplication.translate("Principal", "Domicilio", None, QtGui.QApplication.UnicodeUTF8))
        self.twDatosPersonales.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.twDatosLaborales.isSortingEnabled()
        self.twDatosLaborales.setSortingEnabled(False)
        item = self.twDatosLaborales.item(0, 0)
        item.setText(QtGui.QApplication.translate("Principal", "Nro de Cuil", None, QtGui.QApplication.UnicodeUTF8))
        item = self.twDatosLaborales.item(1, 0)
        item.setText(QtGui.QApplication.translate("Principal", "Fecha de ingreso", None, QtGui.QApplication.UnicodeUTF8))
        item = self.twDatosLaborales.item(2, 0)
        item.setText(QtGui.QApplication.translate("Principal", "Nro de legajo", None, QtGui.QApplication.UnicodeUTF8))
        item = self.twDatosLaborales.item(3, 0)
        item.setText(QtGui.QApplication.translate("Principal", "Situación de revista", None, QtGui.QApplication.UnicodeUTF8))
        item = self.twDatosLaborales.item(4, 0)
        item.setText(QtGui.QApplication.translate("Principal", "Cargo", None, QtGui.QApplication.UnicodeUTF8))
        self.twDatosLaborales.setSortingEnabled(__sortingEnabled)
        self.lblObservaciones.setText(QtGui.QApplication.translate("Principal", "Observaciones:", None, QtGui.QApplication.UnicodeUTF8))
        self.pbEditarObservaciones.setText(QtGui.QApplication.translate("Principal", "Editar", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tDatosLicencias), QtGui.QApplication.translate("Principal", "Empleado", None, QtGui.QApplication.UnicodeUTF8))
        self.menuArchivo.setTitle(QtGui.QApplication.translate("Principal", "Archivo", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAyuda.setTitle(QtGui.QApplication.translate("Principal", "Ayuda", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEmpleado.setTitle(QtGui.QApplication.translate("Principal", "Empleado", None, QtGui.QApplication.UnicodeUTF8))
        self.menuLicencia.setTitle(QtGui.QApplication.translate("Principal", "Licencia", None, QtGui.QApplication.UnicodeUTF8))
        self.aSalir.setText(QtGui.QApplication.translate("Principal", "Salir", None, QtGui.QApplication.UnicodeUTF8))
        self.aSalir.setShortcut(QtGui.QApplication.translate("Principal", "Alt+F4", None, QtGui.QApplication.UnicodeUTF8))
        self.aReiniciar.setText(QtGui.QApplication.translate("Principal", "Reiniciar", None, QtGui.QApplication.UnicodeUTF8))
        self.aReiniciar.setShortcut(QtGui.QApplication.translate("Principal", "Ctrl+Shift+R", None, QtGui.QApplication.UnicodeUTF8))
        self.aAcerca_de.setText(QtGui.QApplication.translate("Principal", "Acerca de", None, QtGui.QApplication.UnicodeUTF8))
        self.aAgregar.setText(QtGui.QApplication.translate("Principal", "Agregar", None, QtGui.QApplication.UnicodeUTF8))
        self.aEditar.setText(QtGui.QApplication.translate("Principal", "Editar", None, QtGui.QApplication.UnicodeUTF8))
        self.aEliminar.setText(QtGui.QApplication.translate("Principal", "Eliminar", None, QtGui.QApplication.UnicodeUTF8))
        self.aAgregarLicencia.setText(QtGui.QApplication.translate("Principal", "Agregar", None, QtGui.QApplication.UnicodeUTF8))
        self.aEditarLicencia.setText(QtGui.QApplication.translate("Principal", "Editar", None, QtGui.QApplication.UnicodeUTF8))
        self.aEliminarLicencia.setText(QtGui.QApplication.translate("Principal", "Eliminar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGrupo_familiar.setText(QtGui.QApplication.translate("Principal", "Grupo familiar", None, QtGui.QApplication.UnicodeUTF8))
        self.aGenerarGrafico.setText(QtGui.QApplication.translate("Principal", "Generar gráfico", None, QtGui.QApplication.UnicodeUTF8))

