#! /usr/bin/python
# coding=utf-8

import os

def main():
	
	archivos = os.listdir(os.getcwd())
	
	for a in archivos[:]:
		if not a.endswith('.ui'):
			archivos.remove(a)
	
	for a in archivos:
		ac = (a[:-3]) + ".py"
		comando = "pyuic4 " + os.getcwd() + "/" + a + " -o " + os.getcwd() + "/" + ac
		os.system(comando)
	
	archivo = open("ui_principal.py", "r")
	contenido = archivo.read()
	archivo.close()
	
	contenido = contenido.replace("../ima", "ima")
	contenido = contenido.replace("Alt+Shift+F4", "Alt+F4")
	
	archivo = open("ui_principal.py", "w")
	archivo.write(contenido)
	archivo.close()
	
	
	return 0

if __name__ == '__main__':
	exit(main())
